runtime: php55
api_version: 1

env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/datahouse;dbname=baza
  MYSQL_USER: root
  MYSQL_PASSWORD: 'zakaria'

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /dashboard.php
  script: dashboard.php

- url: /users.php
  script: users.php

- url: /logout.php
  script: logout.php

- url: /access-token.php
  script: access-token.php

- url: /report.php
  script: report.php

- url: .*
  script: index.php
